apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-news-api
  namespace: hippo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-news-api
  template:
    metadata:
      labels:
        app: jobs-news-api
    spec:
      containers:
      - name: jobs-news-api
        image: ball2550/jobs-news-api:latest
        ports:
        - containerPort: 3006
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "3006"
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-news-service
  namespace: hippo-project
spec:
  selector:
    app: jobs-news-api
  ports:
  - port: 3006
    targetPort: 3006
  type: ClusterIP
