apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-portfolio
  namespace: hippo-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-portfolio
  template:
    metadata:
      labels:
        app: ai-portfolio
    spec:
      containers:
      - name: ai-portfolio
        image: ball2550/ai-portfolio:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "development"
        - name: BACKEND_PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-portfolio-service
  namespace: hippo-project
spec:
  selector:
    app: ai-portfolio
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP
